my_string = input('Введите произвольный текст: ')
character_count = len(my_string)
print("Количество символов: ", character_count)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])